services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy   # installs wget
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: "wangeugene.cc"
      EMAIL: "yuzhen23@icloud.com"
    volumes:
      # Use relative paths for portability (works on EC2 and locally)
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./www:/usr/share/caddy:rw
      - caddy-data:/data
      - caddy-config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

  rule-updater:
    build:
      context: ./rule-updater
    working_dir: /app
    command: ["pnpm", "start"]
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      WWW_DIR: "/app/www"
      # WWW_DIR/config dir contains the config files inside the docker container
    volumes:
      #  Mount the www directory to allow updates, the www folder is the same level as compose.yaml and rule-updater folder
      - ./www:/app/www  

volumes:
  caddy-data:
  caddy-config: